version: '3.8'

networks:
  rinha:
    name: rinha
    driver: bridge

services:
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - api1
            - api2
        ports:
            - 8080:80
        networks:
            - rinha


    api1:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: api1
        container_name: api1
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: rinha
            DB_USER: root
            DB_PASSWORD: password
        depends_on:
            - db
        networks:
            - rinha
        working_dir: /var/www

    api2:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: api2
        container_name: api2
        environment:
            DB_CONNECTION: mysql
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: rinha
            DB_USER: root
            DB_PASSWORD: password
        depends_on:
            - db
        networks:
            - rinha

    db:
        container_name: db
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - 3306:3306
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        networks:
            - rinha
