version: '3.8'

services:
    nginx:
        container_name: nginx
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "9999:9999"
        depends_on:
            - api1
            - api2
        networks:
            - rinha

    api1:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: api1
        container_name: api1
        volumes:
            - ./:/var/www/
        env_file:
            - .env
        expose:
            - 8000
        depends_on:
            - db
        working_dir: /var/www
        networks:
            - rinha

    api2:
        build:
            context: .
            dockerfile: Dockerfile
        hostname: api2
        container_name: api2
        volumes:
            - ./:/var/www/
        env_file:
            - .env
        expose:
            - 8000
        depends_on:
            - db
        networks:
            - rinha

    db:
        container_name: db
        image: mysql:latest
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=password
        ports:
            - "3300:3306"
        volumes:
            - /var/lib/mysql:/var/lib/mysql
        networks:
            - rinha

networks:
    rinha:
        name: rinha
        driver: bridge
