name: 'CI/CD'
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: [self-hosted]
    steps:
      - name: Create .env
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_APP_NAME: 'Laravel'
          envkey_APP_ENV: 'local'
          envkey_APP_KEY: ''
          envkey_APP_DEBUG: true
          envkey_APP_URL: 'http://localhost'
          envkey_DB_CONNECTION: 'mysql'
          envkey_DB_HOST: 'db'
          envkey_DB_PORT: '3306'
          envkey_DB_DATABASE: rinha
          envkey_DB_USERNAME: root
          envkey_DB_PASSWORD: password
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Generate key
        run: php artisan key:generate
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Build docker
        run: docker compose -f docker-compose.yml up -d --build
